### ISSUE TITLE
[WR] Even rows of table not having the correct colour

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#11]
Issue is similar to the issue presented in the following issue: https://github.com/MaribelHearn/maribelhearn.com/issues/4 

This issue happens on both the new layout and the old layout.

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/411ec331a709091a44e854ca859c63a5829f5027](url)
