### ISSUE TITLE
[PoFV] Images not appearing under certain circumstances

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#13]
**Describe the bug**
Image of the playable characters is not visible under certain window circumstances.

**To Reproduce**
1. Meet the requirements of the CSS media query `@media only screen and (max-width: 1100px)`

The site tries to load the link https://maribelhearn.com/assets/pofv/faces80x80.png, but the image does not exist.

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/54dc4bb2b94a44f508ad35ce0c3f68b4f1c82cf2](url)
