### ISSUE TITLE
[All] Wrong icons on dark mode

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#16]
**Describe the bug**
When on dark mode, the wrong icons are displayed. This happens with the icons of `GitHub` and `Source`.

**Screenshots**
![image](https://user-images.githubusercontent.com/101948046/174860582-f2a9d7cd-5fe5-445d-9c65-61cc2f482e8b.png)

**Comment by MaribelHearn** [comment]
This was a cache issue, not specific to dark mode; the icon sheet was cached on browsers, meaning old versions would be kept, even though browsers are supposed to request updated versions of the icon sheet.

Fixed as of 25/6/2022.
