### ISSUE TITLE
[All, home] Non-visible icon on dark theme

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#17]
**Describe the bug**
There exists an icon that is not so visible when on dark mode. The icon is used for the `THWiki Populatiry Poll`. The icon blends in too much with the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/101948046/174860953-de213e86-ba02-4ccc-a9d5-2bfbe2a17562.png)
![image](https://user-images.githubusercontent.com/101948046/174860991-525b1294-0ce3-42f6-b87f-eca69f0bff85.png)

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/b88bf2f3d2ae7219ab305606a76b353ae2294d2d](url)
