### ISSUE TITLE
[Survival Table] Add NMNB option to UM section

### ISSUE THREAD

**Issue by gensakudan** [MaribelHearn/maribelhearn.com#19]
**Is your feature request related to a problem? Please describe.**
I've yet to achieve any challenge clears in UM without using ability cards, therefore most of the options available to me just don't apply. For example, I have an HNN (with cards) with Reimu, but there are only NM or NB options, requiring me to pick one or the other.

**Describe the solution you'd like**
An additional setting for the drop-down lists in the UM line of the survival table labeled `NMNB`.

**Comment by MaribelHearn** [comment]
Feature introduced as of [https://github.com/MaribelHearn/maribelhearn.com/commit/f82f15370db91bdd0325bd8c9c3dc9c92935e4c0](url)
