### ISSUE TITLE
[Survival] Checkboxes instead of dropdown lists

### ISSUE THREAD

**Issue by gensakudan** [MaribelHearn/maribelhearn.com#20]
### The Problem (should you see it as such)
For games that have multiple different conditions, adding all possible permutations of said conditions would make for a very long dropdown list in certain instances, e.g. WBaWC having four different challenge conditions for a total of `4! = 24` possible permutations.

Heck, if you were particularly insane and added conditions to UM for each individual type of card (i.e. active cards, equipment cards, passive cards, and possibly item cards), then the number of permutations for that could be as high as `5! = 120` or even `6! = 720`.

The above, of course, is an extremely unlikely event and is only brought up as an extreme example, or in case ZUN gets *completely* sloshed while working on the next Touhou game and fills it to the brim with mechanics that require upwards of five different conditions.

### The Solution
1. In order to make the survival table more user-friendly (and possibly future-proof), replace the dropdown lists with a group of checkboxes for each individual condition of each individual game. These would be as follows:
    - [x] **1cc** (clear the game without continuing, using all resources and mechanics at your disposal; the below conditions will all assume a 1cc as a prerequisite)
    - [x] **NM** (no miss; clear without losing a single life)
    - [x] **NB** (no bomb: clear without using bombs)
    - [x] **NBB** (no border break, PCB only: clear without getting hit while a Supernatural Border is active)
    - [x] **NV** (no ventora, UFO only: clear without summoning a single UFO)
    - [ ] ~~**NF** (no freeze, GFW only: clear without freezing any bullets by means of holding down the shot button)~~ lmao yeah right
    - [x] **NT** (no trance, TD only: clear without using manual trances)
    - [x] **NR** (no release, HSiFS only: clear without using subseason releases)
    - [x] **NH** (no hyper, WBaWC only: clear without engaging Berserk Roar, i.e. collecting three or more of the same animal token for every five tokens you collect)
    - [x] **NRB** (no roar break, WBaWC only: clear without getting hit during Roaring Mode, i.e. the phase you enter after collecting five tokens of any kind)
    - [x] **NC** (no cards, UM only: clear without equipping any cards, and without purchasing any card from any shop other than the pendulum card)
      - For PoDD and PoFV, this acronym can also be used to mean "no charge": clear without using any charged attacks.
2. The options **N/A** and **Not cleared** are functionally identical to each other due to having no visual distinguishment, and can therefore be consolidated into one setting, which is used when no checkboxes are ticked.
3. If only **1cc** is checked, the table cell is colored green.
4. If any other conditions are checked, it doesn't matter whether **1cc** is checked or not.
5. If **NB** is checked and **NM** isn't, the table cell is colored blue.
6. If **NM** is checked and **NB** isn't, the table cell is colored pink (or whatever you call the color of your choice).
7. If both **NM** and **NB** are checked, the table cell is colored purple.
8. If additional conditions other than **NM** and **NB** are checked, all conditions that apply (including NM and NB) are specified via text within the table cell.
9. If neither **NM** nor **NB** are checked, but one or more of the game-specific conditions are, the logic from Point 8 above applies and the table cell is colored blue (or a fifth color, should you choose to implement that).

**Comment by gensakudan** [comment]
Addendum to point 9: If neither **NM** not **NB** are checked, but one or more of the game-specific conditions are, it could also be possible to just keep the table cell color green instead. I don't know why I tried to overcomplicate that.

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/31c43eeab9526ad841378523ff33543b8dd98e74
