### ISSUE TITLE
[Survival] Add progress table for scene games (StB, DS, ISC, VD)

### ISSUE THREAD

**Issue by gensakudan** [MaribelHearn/maribelhearn.com#21]
### The Problem
They just don't exist lmao. Kinda unfair, too, since you record [your own progress with scene games](https://maribelhearn.com/history).

### The Solution
There are two possible ways of going about this:
1. A second table for all four games, each one having two columns: one for the total number of scenes cleared, and another for the number of scenes cleared with a second condition if it exists. For DS, that would be the number of scenes cleared with Hatate, and for ISC it'd be the number of scenes cleared without items. StB and VD would not use the second column.
2. A separate table for each game, with separate lines for each level or day, and each individual scene with its own table cell. For StB and VD, you'd only have a single checkbox for whether that scene has been cleared or not. For DS and ISC, you could either add a second checkbox (cleared with Hatate and without items respectively), or a dropdown list with three items (`Not cleared`, `Cleared with Aya only`/`Cleared with items`, `Cleared with Aya and Hatate/Cleared without items`).

**Comment by MaribelHearn** [comment]
Implemented as of https://github.com/MaribelHearn/maribelhearn.com/commit/010a8bed3663d083987de8aa879d0177aba23de0
