### ISSUE TITLE
[Gensokyo] Wrong information displayed in tables of StB and DS

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#23]
**Describe the bug**
The information of replays of the games StB and DS are displayed wrongly in the tables.

**To Reproduce**
1. Go to https://maribelhearn.com/gensokyo
2. Click on `Game`
3. Select `StB` or `DS`
4. The information displayed in the tables are wrong.

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/4359dc65b8aab63acd92ae12d329f55696caab43](url)
