### ISSUE TITLE
[Tiers] Selecting multiple images for a tier does not work.

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#24]
**Describe the bug**
It is not possible to add multiple characters to the tier list when using the double click option.

**To Reproduce**
1. Go to `Currently tiering: Characters` (any option works, but I use this as an example)
2. Set the `Tier List View` to be on `Normal`. On the left side, character should be able to be selected.
3. With your LMB, select Kutaka, Yachie and Mayumi. A white outline should appear around the three characters. 
4. With your LMB, quickly double click on Keiki.
5. The following should appear: 
![image](https://user-images.githubusercontent.com/101948046/175788736-0b66e44c-cf77-49ed-9166-2afeb44570ae.png)
6. When clicking on `B`, only Keiki goes to the `B` tier. Nothing happens to the other selected characters .

**Expected behavior**
All four characters should go to the selected tier.

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/a41b95ada6784b53eff33749cc171ae668cfb415](url)
