### ISSUE TITLE
[History] Outdated information

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#25]
**Describe the issue**
One thing mentioned on the History page are no longer relevant.

Maribel Hearn got a UFO LNB a few days ago that has not been updated yet. The link to the video is as follows: https://www.youtube.com/watch?v=NK9wnUwRDbI

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/3a12eab319f0249e3fa3454e54dba7d8c3624cf6](url)
