### ISSUE TITLE
[WR] Column sorting not sorting out GFW correctly.

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#30]
When sorting the 1st column of the table ``Overall Records`` on https://maribelhearn.com/wr, GFW is either 1st or last.

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/f50ae845b7435c4dd26ecfa77e3ab5de7e6181cf
