### ISSUE TITLE
[Credits] Source for Slots page

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#36]
The ``Background Artists`` section has some sources that are marked as ``Unknown source``. Below lists one of the three unknown sources.

Source: https://danbooru.donmai.us/posts/959198?q=nawo_%28peace
Artist name: ``nawo (peace)``

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/e78d1b58a7453df278cf7bb1ed78dcca3628527f
