### ISSUE TITLE
[Tiers] Misaligned options

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#37]
**Describe the bug**
Some options may appear slightly more above than others are.
![image](https://user-images.githubusercontent.com/101948046/190261749-3b7a5e55-22d0-46c2-b239-85faeee6a2e8.png)

**To Reproduce**
1. In the textfield of `Add tier`, enter ``<p``
2. Click on the button `Add tier`. The tier that appears should be empty.
3. Select the created tier. The textfield should say ``<p``.
4. Replace the text ``<p`` by ``<p>``.
5. Press ``Save Changes``

Edit: Alternatively, there is an easier way to reproduce it.
1. In the textfield of `Add tier`, enter ``hello``
2. Click on the button `Add tier`. 
3. Select the created tier.
4. Replace the text ``hello`` by `` `` (nothing).
5. Press ``Save Changes``

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/52410680aeecc3e0b940fc6203184d8c2f55f531
