### ISSUE TITLE
[Tiers] Wrongly displayed text

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#38]
**Describe the bug**
The text ``[tier name] tier removed!`` may appear despite no tier being removed.

**To Reproduce**
1. Select a tier. The window with the header ``Customise Tier`` should appear. 
2. Click on `Remove This Tier`. A pop-up window should appear in the browser asking for a confirmation.
3. On the pop-up window, select ``Cancel``.
4. The text ``[tier name] tier removed!`` appears.

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/52410680aeecc3e0b940fc6203184d8c2f55f531
