### ISSUE TITLE
[Tiers] Incorrect order of elements

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#39]
**Describe the bug**
The order of elements of a tier gets swapped around when the tiers themselves are swapped around.

**To Reproduce**
1. Go to the ``Works`` tiers. Create two tiers.
2. In the first tier, put in the games of th06-th09 in order.
3. In the second tier, put in the games of th10-th12 in order.
4. Drag the second tier and drop it on the first tier. This changes the placement of the tiers, but it also changes the order of elements of the first tier (the order is now th09-th06).

**Expected behavior**
The expected behaviour is for the elements within the tier to not be swapped around.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/101948046/190267557-69209fa6-5cd8-4324-9810-917cda7d7819.png)
After:
![image](https://user-images.githubusercontent.com/101948046/190267618-85a0e97a-657b-457f-87e7-15c93c8185c3.png)

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/4a7b9390dd0905dfb8fbc36340ec850e2f935608
