### ISSUE TITLE
[LNN] Even rows of table not having the correct colour.

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#4]
**Describe the bug**
Even rows of all table may not have the correct colour on dark mode.

**To Reproduce**
1. Set the page to Light Theme
2. Then, set the page from light theme to dark theme on the LNNs page.

**Expected behavior**
Even rows of table should be coloured dark.

**What actually happened**
Even rows of table are light-coloured.

**Screenshots**
![image](https://user-images.githubusercontent.com/101948046/174824665-7c55aa9e-7ab6-4000-8592-85b419ed2bd6.png)

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/411ec331a709091a44e854ca859c63a5829f5027](url)
