### ISSUE TITLE
[Tiers] Typo at Yuki and Mai

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#40]
There is a typo when double clicking on Yuki and Mai. The text that appears is ``Yukiand Mai`` instead of ``Yuki and Mai``

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/52410680aeecc3e0b940fc6203184d8c2f55f531
