### ISSUE TITLE
[Credits] Source for Jargon page

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#41]
The ``Background Artists`` section has some sources that are marked as ``Unknown source``. Below lists one of the two unknown sources.

Source: https://www.pixiv.net/en/artworks/2217502
Artist name: ``結城辰也``

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/a5ef3499f17976c3dd35dd1164a0fe157dbf2f74
