### ISSUE TITLE
[RF] Wrong table and title formatting on TD History page

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#46]
On the page https://maribelhearn.com/royalflare/history/th13 the table and the title are displayed wrongly. 
![image](https://user-images.githubusercontent.com/101948046/216850680-58d30056-d9a3-4416-a8ca-8736c99cf03d.png)

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/b0aa315d0406b4d68b833ee6d54bf51050c8225e
