### ISSUE TITLE
[Survival] Separate LoLK into Pointdevice and Legacy categories

### ISSUE THREAD

**Issue by anomalocarid** [MaribelHearn/maribelhearn.com#47]
# The Problem

LoLK only has a single category which seems to be geared towards Legacy. This doesn't allow players to record their progress on Pointdevice runs.

# The Solution

Split the columns for the Easy, Normal, Hard, and Lunatic difficulties into two, with one column for Legacy and the other for Pointdevice. For Pointdevice, only two dropdowns should be needed, one for 1cc and the other for no bomb (anybody who's silly enough to do NMNB in Pointdevice could just put that down as legacy).

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/e814c1ead99613f193703c45ff4ec31f28b91bfc
