### ISSUE TITLE
Screenshot may be cut off at the bottom on the "Works" tier list page

### ISSUE THREAD

**Issue by anomalocarid** [MaribelHearn/maribelhearn.com#49]
**Describe the bug**
When making a tier list for Lunatic 1cc game difficulty, I noticed in the generated screenshot the bottom tier was being cutoff. See the screenshots for an example. I was using a nonstandard tier header width, but when setting it to the default I still observe the same problem.

**To Reproduce**
1. Go to the [tier list page](https://maribelhearn.com/tiers).
2. Select "Works" from the dropdown to tier works.
3. Fill in the tier list according to the screenshots.
4. In the setting, set "Tier Header width" to 200.
5. Click "Screenshot" and observe the generated screenshot.

**Expected behavior**
The tier list screenshot should include all tiers and not be cut off at the bottom.

**Screenshots**
Screenshot of the cutoff tier list I observed:
![touhou_tier_list_2024_03_25_15_21_20](https://github.com/MaribelHearn/maribelhearn.com/assets/44712387/cdacab46-bd15-4745-88b5-4526a53a9ea8)

Screenshot of the expected tier list (done by screenshotting the entire page and cropping in MS Paint):
![expected_tier_list](https://github.com/MaribelHearn/maribelhearn.com/assets/44712387/bf285776-cb1b-40a9-a2ed-a297ac4249c0)

**Desktop (please complete the following information):**
 - Browser: Google Chrome
 - Version: 122.0.6261.131

**Comment by MaribelHearn** [comment]
Fixed as of https://github.com/MaribelHearn/maribelhearn.com/commit/61fd6e5e3d91ba8fe151e2341e395723dca18155
