### ISSUE TITLE
[LNN] Some columns do not have a properly working sorting order

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#5]
**Describe the bug**
Some columns of the `Player Ranking` table do not have a properly working sorting order. In particular, the columns `No. of LNNS` and `Games LNN'd` are affected by this.

**To Reproduce**
1. Go to the table `Player Ranking`
2. Click on the table header of `No. of LNNs` or `Games LNN'd`. 

**Expected behavior**
The columns would be in a correct sorting order.

**What actually happens**
The columns are not in correct sorting order.

**Screenshots**
![image](https://user-images.githubusercontent.com/101948046/174825791-e3e50c4d-bc21-4f2c-a1d5-b2920794347f.png)

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/fcc7b56d496ef59d18101d8561bd6932e2f1e816](url)
