### ISSUE TITLE
[LNN] The triangle symbol ▴ or ▾ does not appear when sorting a column

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#6]
**Describe the bug**
The triangle symbol ▴ or ▾ does not appear when sorting a column

**To Reproduce**
For this to be done you need to use both tables `Overall Count` and `Player Ranking`. 
1. Go to the table `Player Ranking` and click on the header `Games LNN'd`. Next to the text `Games LNN'd`, the symbol ▾ appears.
2. Go to the table `Overall Count` and click on the header `Different players`. Next to the text `Different players`, the symbol ▾ appears. Next to the text `Games LNN'd`, the symbol ▾ **dis**appears.
3. Go to the table `Player Ranking` and click on the header `Games LNN'd`. Upon (continuously) clicking on the header, no symbol appears. However, the symbol is still present in the column `Different players` of the table `Overall Count`

**Expected behavior**
It is expected for the symbol ▴ or ▾ to appear when clicking on the header `Games LNN'd`, but instead nothing appears.

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/fcc7b56d496ef59d18101d8561bd6932e2f1e816](url)
