### ISSUE TITLE
[Tools] Deadlinks

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#8]
A deadlink is a link that does not work anymore. Below is a list that compiles all deadlinks on the page https://maribelhearn.com/tools.

1. Section `Practice Tools by Riri`, [LoLK](http://www.mediafire.com/Download/88ncjlua3hjrma2/th15_assist_2.2.rar)
2. Section `WBaWC Boss Rush by Plus`, [Download](https://mega.nz/#!e3wwQADS!8I4Rcr9wF-B-hV3b9wbEjGOOI9zbbz8mKj8oY86tWhY)
3. Section `DS Seija by BurntToast12`, [Download](https://mega.co.nz/#!CB4FTBwQ!JhXn6QwNeDTQu_Ys2KNt_mZlV61r8jcBF_FtVrRlcP0)
4. Section `RNG patches by Daikarasu`, [Daikarasu](https://www.twitch.tv/dai_th)
5. Section `Neko Project 21`, [Download](https://sites.google.com/site/np21win/)

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/f8a5673a198917186bef63300926607876567dbf](url)
