### ISSUE TITLE
[Poll] The triangle symbol ▴ or ▾ does not appear when sorting a column

### ISSUE THREAD

**Issue by Nylilsa** [MaribelHearn/maribelhearn.com#9]
See issue https://github.com/MaribelHearn/maribelhearn.com/issues/6

**Comment by MaribelHearn** [comment]
Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/fcc7b56d496ef59d18101d8561bd6932e2f1e816](url)
